# Generated by Django 3.2.25 on 2025-01-16 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20250116_0443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='shipping',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True, verbose_name='Shipping Amount'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='name',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Variant Name'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_items', to='store.product'),
        ),
    ]
